[package]
name = "example_2_cache_slots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2"
revm = { version = "3", features = [ "ethersdb" ]}
tokio = "1"